hydra:
  run:
    dir: outputs/${data.dataname}/${model.modelname}/${experiment}/frames_${data.max_frames}/bs_${machine.batch_size}/
  job: # automatically go to the job folder (needed for hydra > 1.2 with new behavior)
    chdir: true

# Global configurations shared between different modules
experiment: lr-${model.optimizer.lr}
run_name: base

seed: 1234
logger_level: INFO

# Composing nested config with default
defaults:
  - _self_
  - data: tfcovr
  - machine: server
  - trainer: gpu
  - test: null
  - trainer/logger: csv
  - model: aim
  - model/optimizer: adamw
  - model/scheduler: cosine
  - model/loss: null
  - model/ckpt: aim
  - model/loss_terms: si_ti

  - experiment: null
  - experiment2: null

paths: ${machine.paths}

# Flag to validate at the end of every epoch
val: True
evaluate:
  _target_: src.test.${model.basemodel}.utils.evaluate